name: websafe_platform
description: Simple abstraction to be able to detect Web, Android, and iOS without a hard reference to `dart:io`
version: 1.2.0-nullsafety.0
homepage: https://github.com/peiffer-innovations/websafe_platform

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
